filter:
    excluded_paths:
        - tests/*
        - examples/*

before_commands:
    - composer install --prefer-source

build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage-clover.xml'
                coverage:
                    file: 'coverage-clover.xml'
                    format: 'php-clover'

checks:
    php:
        code_rating: true
        duplication: true

tools:
    php_analyzer: true
    php_code_sniffer:
        config:
            standard: "PSR2"
    php_mess_detector: true
