Vagrant.configure("2") do |config|

  config.vm.box = "precise64"
  config.vm.host_name = "arara-process"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.synced_folder("..", "/arara/process", :mount_options => ['dmode=777','fmode=777'])

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file = "default.pp"
    puppet.module_path = "modules"
  end

end
